routes/web.php
<?php



use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(env('REDIRECT_HTTPS')){
    URL::forceScheme('https');
}

Route::get('/', 'Content\WelcomeController@index')->name('/');
Route::post('/sendEmail', 'Content\WelcomeController@sendEmail')->name('sendEmail');
Route::get('/setLocale/{lang}', 'Content\WelcomeController@setLocale')->name('setLocale');

Route::get('/service/{slug}','Content\ProjectController@showService')->name('service');
Route::get('/project/{slug}','Content\ProjectController@showProject')->name('project');

Route::resource('dashboard','Admin\DashboardController');
Route::resource('projects','Admin\ProjectController');
Route::resource('services','Admin\ServiceController');
Route::resource('reviews','Admin\ReviewController');
Route::resource('blog','Admin\BlogController');
Route::resource('messages','Admin\MessagesController');
Route::resource('team','Admin\TeamController');
Route::resource('gallery','Admin\GalleryController');
Route::resource('property','Admin\PropertyController');
Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    //
}

app/Http/Controllers/Admin/GalleryController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Gallery;
use App\Galleryimage;
use App\Http\Controllers\AdminController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class GalleryController extends AdminController
{

    public function __construct()
    {
        parent::__construct();
        $this->middleware('auth');

    }


    public function index(){
        $galleries = Gallery::where('active','=','1')->where('deleted','=','0')->orderBy('id','desc')->get();
        return view($this->path.'gallery.show',['data'=>$galleries]);
    }

    public function create(){
        return view($this->path.'gallery.create');
    }

    public function edit($lang,$id){
        $gallery = Gallery::find($id);
        $images = Galleryimage::where('gallery_id','=',$id)->get();
        $imagesRes = array();
        if(!empty($images)){
            foreach($images as $key => $image){
                $exploded = explode('.',$image['name']);
                $imagesRes[$key]['name'] = asset('uploads/'.$exploded[0].'-thumb.'.$exploded[1]);
                $imagesRes[$key]['id'] = $image['id'];
            }
        }

        return view($this->path.'gallery.edit',['gallery'=>$gallery,'images'=>$imagesRes]);
    }

    public function update($lang,$id,Request $request){

        $data = $request->all();

        $gallery = array(
            'internal_name' => $data['internal_name'],
        );

        $res = Gallery::where('id','=',$id)->update($gallery);

        $images = array();
        if(isset($data['image']) && !empty($data['image'])){
            $files = $request->allFiles();
            if(isset($files['image']) && !empty($files['image'])){
                foreach($files['image'] as $image){
                    $time = uniqid().'_'.time();
                    $images[] = $time.'.jpg';
                    foreach($this->sizes as $fit => $size ){
                        $img = Image::make($image)->fit($size)->encode('jpg');
                        $name = $time .'-'.$fit.'.jpg';
                        Storage::disk('public')->put($name, $img);
                    }
                }
            }
        }

        $multipleImagesInsert = array();
        if(!empty($images)){
            foreach($images as $image){
                $imageInsert = array(
                    'gallery_id' => $id,
                    'name' => $image,
                    'created_at' => date('Y-m-d H:i:s')
                );
                $multipleImagesInsert[] = $imageInsert;
            }
        }

        if(!empty($multipleImagesInsert)){
            Galleryimage::insert($multipleImagesInsert);
        }

        return redirect(route('gallery.index'));
    }

    public function destroy($lang,Request $request){
        $data = $request->all();

        $img = Galleryimage::find($data['id']);

        $exploded = explode('.',$img['name']);
        foreach($this->sizes as $type => $size){
            Storage::delete('public/image/'.$exploded[0].'-'.$type.'.'.$exploded[1]);
        }

        Galleryimage::where('id','=',$data['id'])->delete();

        return response(array('status' => '1'));
    }

    public function store(Request $request){
        $data = $request->all();
        $gallery = array(
            'internal_name' => $data['internal_name'],
            'active' => '1',
            'deleted'=>'0',
            'created_at' => date('Y-m-d H:i:s')
        );

        $gallery_id = Gallery::insertGetId($gallery);

        $images = array();
        if(isset($data['image']) && !empty($data['image'])){
            $files = $request->allFiles();
            if(isset($files['image']) && !empty($files['image'])){
                foreach($files['image'] as $image){
                    $time = uniqid().'_'.time();
                    $images[] = $time.'.jpg';
                    foreach($this->sizes as $fit => $size ){
                        $img = Image::make($image)->fit($size)->encode('jpg');
                        $name = $time .'-'.$fit.'.jpg';
                        Storage::put($name, $img);
                        Storage::move($name, 'public/image/' . $name);
                    }
                }
            }
        }

        $multipleImagesInsert = array();
        if(!empty($images)){
            foreach($images as $image){
                $imageInsert = array(
                    'gallery_id' => $gallery_id,
                    'name' => $image,
                    'created_at' => date('Y-m-d H:i:s')
                );
                $multipleImagesInsert[] = $imageInsert;
            }
        }

        if(!empty($multipleImagesInsert)){
            Galleryimage::insert($multipleImagesInsert);
        }

        return redirect(route('gallery.index'));
    }

}

app/Http/Controllers/Content/ProjectController.php
<?php


namespace App\Http\Controllers\Content;


use App\Http\Controllers\Controller;

class ProjectController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function showProject($lang,$slug){

        $content = $this->getContent();
        $content['row'] = $this->findMyRow($this->getContent('projects'),$slug);
        $content['lang'] = $lang;

        return view('_project.show',$content);
    }

    public function showService($lang,$slug){
        $content = $this->getContent();
        $content['row'] = $this->findMyRow($this->getContent('services'),$slug);
        $content['lang'] = $lang;

        return view('_project.show',$content);
    }

    private function findMyRow($content,$slug,$field = 'slug'){
       $my_item = array();

       if(!empty($content)){
           foreach($content as $content_item){
               if($content_item[$field] == $slug){
                   $my_item = $content_item;
                   break;
               }
           }
       }

       //dd($my_item);
       return $my_item;
    }
}

app/Http/Controllers/Content/WelcomeController.php
<?php

namespace App\Http\Controllers\Content;

use App\Http\Controllers\Controller;
use App\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class WelcomeController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function index(){
        return view('welcome',$this->getContent());
    }

    public function setLocale($lang){
        if(in_array($lang,$this->available_languages)){
            App::setLocale($lang);
        }
        return redirect()->route('/');

    }

    public function sendEmail(Request $request){

        $data = $request->all();

        $property = $this->getContent('property');

        Mail::send('_email.base', array('data'=>$data) , function ($m) use ($data,$property) {
            $m->from('no-reply@incasarl.fr', 'Inca Sarl System');
            $m->to(isset($property['email']) && !empty($property['email']) ? $property['email'] : $this->email)->subject('New message from website - '.$data['subject']);
        });

        unset($data['_token']);
        $data['active'] = '1';
        $data['deleted'] = '0';
        $data['created_at'] = date('Y-m-d H:i:s');
        Message::insert($data);

        Session::put('sended_email_at',date('Y-m-d H:i:s'));
        return redirect(url('/'.$this->currentLang.'#contact'));
    }


}

resources/views/_admin/_content/gallery/create.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Galéria'}}</h5>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <form action="{{route('gallery.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>interný názov</label>
                                    <input type="text" name="internal_name" class="form-control" required>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <div id="cloned-wrapper" class="row">
                                    <div class="col-md-12 col-xs-12 col-sm-12 clone-row">
                                        <div class="row">
                                            <div class="col-xs-10 col-sm-10 col-md-10">
                                                <div class="form-group">
                                                    <label>Obrázok</label>
                                                    <input type="file" class="form-control clone-input" name="image[0]">
                                                </div>
                                            </div>
                                            <div class="col-xs-2 col-sm-2 col-md-2">
                                                <button type="button" class="btn btn-success clone" style="margin-top:27px;">+</button>
                                                <button type="button" class="btn btn-danger remove" disabled style="margin-top:27px;">-</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary w-100">Uložiť</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        var counter = 1;
        $(document).on('click','.clone',function(){
            var cloned = $(this).closest('.clone-row').clone();
            cloned.find('.clone-input').val('');
            cloned.find('.clone-input').attr('name','image['+counter+']');
            cloned.find('.remove').attr('disabled',false);
            $('#cloned-wrapper').append(cloned);
            counter++;
            checkButtons();
        });
        $(document).on('click','.remove',function(){
            $(this).closest('.clone-row').remove();
            checkButtons();
        });

        var checkButtons = function(){
            var row = $('.clone-row');
            if(row.length>1){
                $('.remove').attr('disabled',false);
            }
            else{
                $('.remove').attr('disabled',true);
            }
        }
    </script>
@endsection

resources/views/_admin/_content/gallery/edit.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Galéria'}}</h5>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <form action="{{route('gallery.update',[$gallery['id']])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>interný názov</label>
                                    <input type="text" name="internal_name" class="form-control" value="{{$gallery['internal_name']}}" required>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <h5>Existujúce obrázky v galérii</h5>
                                <div class="row">
                                    @if(isset($images) && !empty($images))
                                        @foreach($images as $image)
                                            <div class="col-md-3 img-remove cursor-pointer" data-id="{{$image['id']}}" style="height:200px;">
                                                <div style="width:100%;height:100%;background-image:url('{{$image['name']}}');background-position:center;background-size:cover;background-repeat: no-repeat;"></div>
                                            </div>
                                        @endforeach
                                    @endif
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <div id="cloned-wrapper" class="row">
                                    <div class="col-md-12 col-xs-12 col-sm-12 clone-row">
                                        <div class="row">
                                            <div class="col-xs-10 col-sm-10 col-md-10">
                                                <div class="form-group">
                                                    <label>Obrázok</label>
                                                    <input type="file" class="form-control clone-input" name="image[0]">
                                                </div>
                                            </div>
                                            <div class="col-xs-2 col-sm-2 col-md-2">
                                                <button type="button" class="btn btn-success clone" style="margin-top:27px;">+</button>
                                                <button type="button" class="btn btn-danger remove" disabled style="margin-top:27px;">-</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary w-100">Uložiť</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>

        $('.img-remove').on('click',function(){
            if(confirm('Naozaj to chces zmazat?')){
                $(this).remove();
                $.ajax({
                    url:'{{route('gallery.destroy',['id'])}}',
                    type:'post',
                    data:{_method:'delete',_token:'{{csrf_token()}}',id:$(this).data().id},
                    dataType:'json',
                    success:function(data){

                    }
                });
            }
        });

        var counter = 1;
        $(document).on('click','.clone',function(){
            var cloned = $(this).closest('.clone-row').clone();
            cloned.find('.clone-input').val('');
            cloned.find('.clone-input').attr('name','image['+counter+']');
            cloned.find('.remove').attr('disabled',false);
            $('#cloned-wrapper').append(cloned);
            counter++;
            checkButtons();
        });
        $(document).on('click','.remove',function(){
            $(this).closest('.clone-row').remove();
            checkButtons();
        });

        var checkButtons = function(){
            var row = $('.clone-row');
            if(row.length>1){
                $('.remove').attr('disabled',false);
            }
            else{
                $('.remove').attr('disabled',true);
            }
        }
    </script>
@endsection

resources/views/_admin/_content/gallery/show.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Galérie'}}</h5>
                        </div>
                        <div class="col-md-6">
                            <a href="{{route('gallery.create')}}" class="btn btn-primary w-100">Vytvoriť</a>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>interný názov</th>
                                <th>akcia</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($data) && !empty($data))
                                @foreach($data as $d)
                                    <tr>
                                        <td>{{$d['id']}}</td>
                                        <td>{{$d['internal_name']}}</td>
                                        <td>
                                            <div class="row">
                                                <div class="col-md-12 ml-auto text-center">
                                                    <a href="{{route('gallery.edit',[$d['id']])}}" class="btn btn-sm btn-info"> Upraviť</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection