routes/web.php
<?php



use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(env('REDIRECT_HTTPS')){
    URL::forceScheme('https');
}

Route::get('/', 'Content\WelcomeController@index')->name('/');
Route::post('/sendEmail', 'Content\WelcomeController@sendEmail')->name('sendEmail');
Route::get('/setLocale/{lang}', 'Content\WelcomeController@setLocale')->name('setLocale');

Route::get('/service/{slug}','Content\ProjectController@showService')->name('service');
Route::get('/project/{slug}','Content\ProjectController@showProject')->name('project');

Route::resource('dashboard','Admin\DashboardController');
Route::resource('projects','Admin\ProjectController');
Route::resource('services','Admin\ServiceController');
Route::resource('reviews','Admin\ReviewController');
Route::resource('blog','Admin\BlogController');
Route::resource('messages','Admin\MessagesController');
Route::resource('team','Admin\TeamController');
Route::resource('gallery','Admin\GalleryController');
Route::resource('property','Admin\PropertyController');
Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = ['active'];
}

app/Http/Controllers/Admin/ProjectController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Gallery;
use App\Project;
use App\Http\Controllers\AdminController;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProjectController extends AdminController
{

    public function __construct()
    {
        parent::__construct();
    }
    public function index(){
        $projects = Project::where('deleted','=','0')->get();
        return view($this->path.'projects.show',['data'=>$projects]);
    }

    public function create(){
        $galleries = Gallery::where('active','=','1')->where('deleted','=','0')->orderBy('id','desc')->get();
        return view($this->path.'projects.create',['galleries'=>$galleries]);
    }

    public function edit($lang,$id){
        $project = Project::find($id);
        $galleries = Gallery::where('active','=','1')->where('deleted','=','0')->orderBy('id','desc')->get();

        $project['name'] = json_decode($project['names'],TRUE);
        $project['category'] = json_decode($project['categories'],TRUE);
        $project['text'] = json_decode($project['texts'],TRUE);

        return view($this->path.'projects.edit',['project'=>$project,'galleries'=>$galleries]);
    }

    public function store(Request $request){
        $data = $request->all();

        unset($data['_token']);
        unset($data['files']);
        if(isset($data['name']) && !empty($data['name'])){
            $data['names'] = json_encode($data['name']);
            unset($data['name']);
        }
        if(isset($data['category']) && !empty($data['category'])){
            $data['categories'] = json_encode($data['category']);
            unset($data['category']);
        }
        if(isset($data['text']) && !empty($data['text'])){
            $data['texts'] = json_encode($data['text']);
            unset($data['text']);
        }
        if(isset($data['slug']) && !empty($data['slug'])){
            $data['slug'] = Str::slug($data['slug']);
        }
        else{
            $data['slug'] = Str::slug($data['internal_name']);
        }


        $data['created_at'] = date('Y-m-d H:i:s');

        Project::insert($data);

        $this->deleteFromCache('projects');
        return redirect(route('projects.index'));

    }

    public function update($lang,$id,Request $request){
        $data = $request->input();

        //dd($data);
        unset($data['_token']);
        unset($data['files']);
        unset($data['_method']);
        if(isset($data['name']) && !empty($data['name'])){
            $data['names'] = json_encode($data['name']);
            unset($data['name']);
        }
        if(isset($data['category']) && !empty($data['category'])){
            $data['categories'] = json_encode($data['category']);
            unset($data['category']);
        }
        if(isset($data['text']) && !empty($data['text'])){
            $data['texts'] = json_encode($data['text']);
            unset($data['text']);
        }
        if(isset($data['slug']) && !empty($data['slug'])){
            $data['slug'] = Str::slug($data['slug']);
        }
        else{
            if(isset($data['internal_name']) && !empty($data['internal_name'])){
                $data['slug'] = Str::slug($data['internal_name']);
            }
        }

        $data['updated_at'] = date('Y-m-d H:i:s');

        Project::where('id','=',$id)->update($data);

        $this->deleteFromCache('projects');
        return redirect(route('projects.index'));
    }
}

app/Http/Controllers/Content/ProjectController.php
<?php


namespace App\Http\Controllers\Content;


use App\Http\Controllers\Controller;

class ProjectController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function showProject($lang,$slug){

        $content = $this->getContent();
        $content['row'] = $this->findMyRow($this->getContent('projects'),$slug);
        $content['lang'] = $lang;

        return view('_project.show',$content);
    }

    public function showService($lang,$slug){
        $content = $this->getContent();
        $content['row'] = $this->findMyRow($this->getContent('services'),$slug);
        $content['lang'] = $lang;

        return view('_project.show',$content);
    }

    private function findMyRow($content,$slug,$field = 'slug'){
       $my_item = array();

       if(!empty($content)){
           foreach($content as $content_item){
               if($content_item[$field] == $slug){
                   $my_item = $content_item;
                   break;
               }
           }
       }

       //dd($my_item);
       return $my_item;
    }
}

app/Http/Controllers/Content/WelcomeController.php
<?php

namespace App\Http\Controllers\Content;

use App\Http\Controllers\Controller;
use App\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class WelcomeController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function index(){
        return view('welcome',$this->getContent());
    }

    public function setLocale($lang){
        if(in_array($lang,$this->available_languages)){
            App::setLocale($lang);
        }
        return redirect()->route('/');

    }

    public function sendEmail(Request $request){

        $data = $request->all();

        $property = $this->getContent('property');

        Mail::send('_email.base', array('data'=>$data) , function ($m) use ($data,$property) {
            $m->from('no-reply@incasarl.fr', 'Inca Sarl System');
            $m->to(isset($property['email']) && !empty($property['email']) ? $property['email'] : $this->email)->subject('New message from website - '.$data['subject']);
        });

        unset($data['_token']);
        $data['active'] = '1';
        $data['deleted'] = '0';
        $data['created_at'] = date('Y-m-d H:i:s');
        Message::insert($data);

        Session::put('sended_email_at',date('Y-m-d H:i:s'));
        return redirect(url('/'.$this->currentLang.'#contact'));
    }


}

resources/views/_admin/_content/projects/create.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Reviews'}}</h5>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <form action="{{route('projects.store')}}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>interný názov</label>
                                    <input type="text" name="internal_name" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Galéria</label>
                                    <select name="gallery_id" class="form-control">
                                        <option value="">Žiadna galéria</option>
                                        @if(isset($galleries) && !empty($galleries))
                                            @foreach($galleries as $gallery)
                                                <option value="{{$gallery['id']}}">{{$gallery['internal_name']}}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Názov en</label>
                                    <input type="text" class="form-control" name="name[en]">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Názov fr</label>
                                    <input type="text" class="form-control" name="name[fr]">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Kategória en</label>
                                    <input type="text" class="form-control" name="category[en]">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Kategória fr</label>
                                    <input type="text" class="form-control" name="category[fr]">
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Slug</label>
                                    <input type="text" class="form-control" name="slug">
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text fr</label>
                                    <textarea name="text[fr]" cols="30" rows="10" class="form-control summernote" required>{{isset($property['text']['fr']) ? $property['text']['fr'] : ''}}</textarea>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text en</label>
                                    <textarea name="text[en]" cols="30" rows="10" class="form-control summernote" required>{{isset($property['text']['en']) ? $property['text']['en'] : ''}}</textarea>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <button class="btn btn-primary w-100">Uložiť</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.summernote').summernote({
                height: 120,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                ]
            });
        });
    </script>
@endsection

resources/views/_admin/_content/projects/edit.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Reviews'}}</h5>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <form action="{{route('projects.update',[$project['id']])}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>interný názov</label>
                                    <input type="text" name="internal_name" value="{{$project['internal_name']}}" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Galéria</label>
                                    <select name="gallery_id" class="form-control">
                                        <option value="">Žiadna galéria</option>
                                        @if(isset($galleries) && !empty($galleries))
                                            @foreach($galleries as $gallery)
                                                <option {{$project['gallery_id'] == $gallery['id'] ? 'selected' : ''}} value="{{$gallery['id']}}">{{$gallery['internal_name']}}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Názov en</label>
                                    <input type="text" value="{{$project['name']['en']}}" class="form-control" name="name[en]">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Názov fr</label>
                                    <input type="text" value="{{$project['name']['fr']}}" class="form-control" name="name[fr]">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Kategória en</label>
                                    <input type="text" value="{{$project['category']['en']}}" class="form-control" name="category[en]">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Kategória fr</label>
                                    <input type="text" value="{{$project['category']['fr']}}" class="form-control" name="category[fr]">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Slug</label>
                                    <input type="text" class="form-control" name="slug" value="{{$project['slug']}}">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text fr</label>
                                    <textarea name="text[fr]" cols="30" rows="10" class="form-control summernote" required>{{isset($project['text']['fr']) ? $project['text']['fr'] : ''}}</textarea>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text en</label>
                                    <textarea name="text[en]" cols="30" rows="10" class="form-control summernote" required>{{isset($project['text']['en']) ? $project['text']['en'] : ''}}</textarea>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <button class="btn btn-primary w-100">Uložiť</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.summernote').summernote({
                height: 120,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                ]
            });
        });
    </script>
@endsection

resources/views/_admin/_content/projects/show.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Projekty'}}</h5>
                        </div>
                        <div class="col-md-6">
                            <a href="{{route('projects.create')}}" class="btn btn-primary w-100">Vytvoriť</a>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>interný názov</th>
                                <th>aktivne</th>
                                <th>akcia</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($data) && !empty($data))
                                @foreach($data as $d)
                                    <tr>
                                        <td>{{$d['id']}}</td>
                                        <td>{{$d['internal_name']}}</td>
                                        <td>
                                            <form action="{{route('projects.update',[$d['id']])}}" method="post">
                                                <div class="row">
                                                    <div class="col-md-12 ml-auto text-center">
                                                        @method('PUT')
                                                        @csrf
                                                        <input type="hidden" name="active" value="{{$d['active'] == '1' ? '0' : '1'}}">
                                                        <button class="btn btn-sm btn-{{$d['active'] == '1' ? 'success' : 'warning'}}">{{$d['active'] == '1' ? 'Aktívne' : 'Neaktívne'}}</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </td>
                                        <td>
                                            <div class="row">
                                                <div class="col-md-12 ml-auto text-center">
                                                    <a href="{{route('projects.edit',[$d['id']])}}" class="btn btn-sm btn-info"> Upraviť</a>
                                                    <form action="{{route('projects.update',[$d['id']])}}" method="post" style="display:inline-block">
                                                        <div class="row">
                                                            <div class="col-md-12 ml-auto text-center">
                                                                @method('PUT')
                                                                @csrf
                                                                <input type="hidden" name="deleted" value="1">
                                                                <button class="btn btn-sm btn-danger">Zmazať</button>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection