routes/web.php
<?php



use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if(env('REDIRECT_HTTPS')){
    URL::forceScheme('https');
}

Route::get('/', 'Content\WelcomeController@index')->name('/');
Route::post('/sendEmail', 'Content\WelcomeController@sendEmail')->name('sendEmail');
Route::get('/setLocale/{lang}', 'Content\WelcomeController@setLocale')->name('setLocale');

Route::get('/service/{slug}','Content\ProjectController@showService')->name('service');
Route::get('/project/{slug}','Content\ProjectController@showProject')->name('project');

Route::resource('dashboard','Admin\DashboardController');
Route::resource('projects','Admin\ProjectController');
Route::resource('services','Admin\ServiceController');
Route::resource('reviews','Admin\ReviewController');
Route::resource('blog','Admin\BlogController');
Route::resource('messages','Admin\MessagesController');
Route::resource('team','Admin\TeamController');
Route::resource('gallery','Admin\GalleryController');
Route::resource('property','Admin\PropertyController');
Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Http/Controllers/Admin/ReviewController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Http\Controllers\AdminController;
use App\Review;
use Illuminate\Http\Request;

class ReviewController extends AdminController
{

    public function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
        $data = Review::all();
        return view($this->path . 'reviews.show', ['data' => $data]);
    }

    public function create(){
        return view($this->path.'reviews.create');
    }

    public function store(Request $request){
        $data = $request->all();
        unset($data['_token']);
        $data['created_at'] = date('Y-m-d H:i:s');
        $data['texts'] = json_encode($data['text']);
        unset($data['text']);
        $data['active'] = '1';
        $data['deleted'] = '0';

        Review::insert($data);
        $this->deleteFromCache('reviews');
        return redirect(route('reviews.index'));
    }

    public function edit($lang,$id){
        $review = Review::find($id);
        $review['text'] = json_decode($review['texts'],TRUE);
        return view($this->path.'reviews.edit',['review'=>$review]);
    }

    public function update($lang,$id,Request $request){
        $data = $request->all();
        unset($data['_token']);
        unset($data['_method']);
        if(isset($data['text'])){
            $data['texts'] = json_encode($data['text']);
            unset($data['text']);
        }
        Review::where('id','=',$id)->update($data);
        $this->deleteFromCache('reviews');
        return redirect(route('reviews.index'));
    }
}

app/Http/Controllers/Content/ProjectController.php
<?php


namespace App\Http\Controllers\Content;


use App\Http\Controllers\Controller;

class ProjectController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function showProject($lang,$slug){

        $content = $this->getContent();
        $content['row'] = $this->findMyRow($this->getContent('projects'),$slug);
        $content['lang'] = $lang;

        return view('_project.show',$content);
    }

    public function showService($lang,$slug){
        $content = $this->getContent();
        $content['row'] = $this->findMyRow($this->getContent('services'),$slug);
        $content['lang'] = $lang;

        return view('_project.show',$content);
    }

    private function findMyRow($content,$slug,$field = 'slug'){
       $my_item = array();

       if(!empty($content)){
           foreach($content as $content_item){
               if($content_item[$field] == $slug){
                   $my_item = $content_item;
                   break;
               }
           }
       }

       //dd($my_item);
       return $my_item;
    }
}

app/Http/Controllers/Content/WelcomeController.php
<?php

namespace App\Http\Controllers\Content;

use App\Http\Controllers\Controller;
use App\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;

class WelcomeController extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function index(){
        return view('welcome',$this->getContent());
    }

    public function setLocale($lang){
        if(in_array($lang,$this->available_languages)){
            App::setLocale($lang);
        }
        return redirect()->route('/');

    }

    public function sendEmail(Request $request){

        $data = $request->all();

        $property = $this->getContent('property');

        Mail::send('_email.base', array('data'=>$data) , function ($m) use ($data,$property) {
            $m->from('no-reply@incasarl.fr', 'Inca Sarl System');
            $m->to(isset($property['email']) && !empty($property['email']) ? $property['email'] : $this->email)->subject('New message from website - '.$data['subject']);
        });

        unset($data['_token']);
        $data['active'] = '1';
        $data['deleted'] = '0';
        $data['created_at'] = date('Y-m-d H:i:s');
        Message::insert($data);

        Session::put('sended_email_at',date('Y-m-d H:i:s'));
        return redirect(url('/'.$this->currentLang.'#contact'));
    }


}

resources/views/_admin/_content/reviews/create.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Reviews'}}</h5>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <form action="{{route('reviews.store')}}" method="post">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>interný názov</label>
                                    <input type="text" name="internal_name" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>meno</label>
                                    <input type="text" name="name" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>práca</label>
                                    <input type="text" name="work" class="form-control" required>
                                </div>
                            </div>
                            <legend></legend>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Text fr</label>
                                        <textarea name="text[fr]" cols="30" rows="10" class="form-control" required></textarea>
                                    </div>
                                </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text en</label>
                                    <textarea name="text[en]" cols="30" rows="10" class="form-control" required></textarea>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <button class="btn btn-primary w-100">Uložiť</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/_admin/_content/reviews/edit.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Reviews'}}</h5>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <form action="{{route('reviews.update',[$review['id']])}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>interný názov</label>
                                    <input type="text" name="internal_name" class="form-control" value="{{$review['internal_name']}}" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>meno</label>
                                    <input type="text" name="name" class="form-control" value="{{$review['name']}}" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>práca</label>
                                    <input type="text" name="work" class="form-control" value="{{$review['work']}}" required>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text fr</label>
                                    <textarea name="text[fr]" cols="30" rows="10" class="form-control" required>{{$review['text']['fr']}}</textarea>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Text en</label>
                                    <textarea name="text[en]" cols="30" rows="10" class="form-control" required>{{$review['text']['en']}}</textarea>
                                </div>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <button class="btn btn-primary w-100">Uložiť</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/_admin/_content/reviews/show.blade.php
@extends('_admin._layouts.master')

@section('content')
    <div class="content-wrapper">
        <div class="content">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>{{'Reviews'}}</h5>
                        </div>
                        <div class="col-md-6">
                            <a href="{{route('reviews.create')}}" class="btn btn-primary w-100">Vytvoriť</a>
                        </div>
                    </div>
                    <legend></legend>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>interný názov</th>
                                <th>meno</th>
                                <th>povolanie</th>
                                <th>aktivne</th>
                                <th>akcia</th>
                            </tr>
                            </thead>
                            <tbody>
                                @if(isset($data) && !empty($data))
                                    @foreach($data as $d)
                                        <tr>
                                            <td>{{$d['id']}}</td>
                                            <td>{{$d['internal_name']}}</td>
                                            <td>{{$d['name']}}</td>
                                            <td>{{$d['work']}}</td>
                                            <td>
                                                <form action="{{route('reviews.update',[$d['id']])}}" method="post">
                                                    <div class="row">
                                                        <div class="col-md-12 ml-auto text-center">
                                                            @method('PUT')
                                                            @csrf
                                                            <input type="hidden" name="active" value="{{$d['active'] == '1' ? '0' : '1'}}">
                                                            <button class="btn btn-sm btn-{{$d['active'] == '1' ? 'success' : 'warning'}}">{{$d['active'] == '1' ? 'Aktívne' : 'Neaktívne'}}</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </td>
                                            <td>
                                                <div class="row">
                                                    <div class="col-md-12 ml-auto text-center">
                                                        <a href="{{route('reviews.edit',[$d['id']])}}" class="btn btn-sm btn-info"> Upraviť</a>
                                                        <form action="{{route('reviews.update',[$d['id']])}}" method="post" style="display:inline-block">
                                                            <div class="row">
                                                                <div class="col-md-12 ml-auto text-center">
                                                                    @method('PUT')
                                                                    @csrf
                                                                    <input type="hidden" name="deleted" value="0">
                                                                    <button class="btn btn-sm btn-danger">Zmazať</button>
                                                                </div>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection